### ISSUE TITLE
Review Ticket T3: TT0

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#1]
Please put your comments below

- [x] jekyll page [link](https://christinlee367.github.io/)
- [x] 5.1, 5.2 notes and actions [link](https://github.com/christinlee367/christinlee367.github.io/blob/main/README.md)
- [x] rep.lit runtime [link](https://replit.com/@ChristinaLee6/NovelShimmeringCompilers#main.py)
- [x] Individual GitHub repo on repl.it [link](https://replit.com/@ChristinaLee6/christinlee367githubio-4#README.md)

**Comment by arushi10** [comment]
5.1, 5.2 Notes + Actions - 1/1

Replit  Challenges - 0.75/1
All challenges working except keypad

Create Task - 1/1
