### ISSUE TITLE
AP Exams Week 1 - Proctored MCQ - Quiz5

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#11]
# Graded by Sanvi Pal: 11:35-12:12PM PST May 6, 2022: 2/2
- [x] GH Indi Page, Review Ticket, Crossover graded, Study Plan
- [x] Quiz5 MCQ results >50%, (1 or 0) and test corrections
[link](https://christinlee367.github.io/finalMCQ)

**Comment by sanvi1855544** [comment]
2/2

The MCQ shows significant improvement from last week. The reflections are very insightful and make me realize that you are well prepped for this test. My advice would be to revise the concepts but stop the heavy studying. Relax and you will do well!
