### ISSUE TITLE
Week 9: Review Ticket

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#12]
[link](https://github.com/christinlee367/womenInSTEMandDavid/tree/main/templates/awards)
 - wall of fame
 - nighthawks at a glance
 - currently has filler cards

**Comment by yolandayangg** [comment]
Everything looks great; although the CRUD is not working at the moment it shows that at least 5 hours of code has been done. She made cards that you can hover over to find more details about the player, which is extremely creative and functional towards the purpose of the lacrosse website. Overall great job; 1.8/2
