### ISSUE TITLE
Review Ticket: T3 W2 Lists and Loops

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#3]
Please put your comments below
## 4.85/5
[GitHub Page for Christina](https://christinlee367.github.io/)
[Rep.lit](https://replit.com/@ChristinaLee6/NovelShimmeringCompilers#fib.py)
[Team GitHub Page](https://christinlee367.github.io/womenInSTEMandDavid/)

GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions
- [x] 1- One Check 5.3
- [x] 1- One Check 5.4
GitHub page that documents key learnings and code snippets using GitHub and replit.
- [x] InfoDB lists
1 - One Check for New Data, minimum of 4 items
- [x] InfoDB loops
- [x] 1- One Check For Loop running and sensible output
- [x] 1- One Check While Loop running and sensible output
- [x] 1- One Check Recursion running and sensible output
- [x] Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
4- Four checks: Algorithm and code with comments, Prints result, Prints Complete List, Work on complex sequence with multiple words, spaces, special characters
- [x] 1- One check: comments and documentation throughout

INDIVIDUAL to send (Indi score: Checks/9 = score/3) + Team Score
Two DMs for Mortensen, Team Channel for Naidu
Review ticket with total score, include teams score from Friday (n/5) and name of grader next to score.
GitHub pages

**Comment by AadyaDaita** [comment]
### Individual GitHub Page Grading
**9/9 or 3/3**
GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions
- [x]  1- One Check 5.3
- [x]  1- One Check 5.4

GitHub page that documents key learnings and code snippets using GitHub and replit.
 InfoDB lists

- [x] 1 - One Check for New Data, minimum of 4 items 
  - [x] InfoDB loops

- [x] 1- One Check For Loop running and sensible output
- [x]  1- One Check While Loop running and sensible output
- [x]  1- One Check Recursion running and sensible output

Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)

- [x] 4- Four checks: Algorithm and code with comments, Prints result, Prints Complete List, Work on complex sequence with multiple words, spaces, special characters
- [x] 1- One check: comments and documentation throughout

INDIVIDUAL to send (Indi score: Checks/9 = score/3) + Team Score

1. Two DMs for Mortensen, Team Channel for Naidu
2. Review ticket with total score, include teams score from Friday (n/5) and name of grader next to score.
3. GitHub pages
