### ISSUE TITLE
Review Ticket T3: Classy Functions

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#4]
## Grader: Avinh Huynh: Indi score 3.8/3 + Team Score: 2/2 = 5.8/5
[GitHub Pages](https://christinlee367.github.io/) , Review Ticket
Scrum Team GitHub pages (2 points) 
Individual GitHub pages (3 points) - Checkpoint Grading
- [ ] Organize files, directories and menus for the first 3 weeks. 
- [ ] Write Factorial function using classes, providing implementation of call.
- [ ] Select your own Math function. Write it in Imperative and OOP form.
- [ ] Extra Credit(1 point). Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.

**Comment by SlimeyTurtles** [comment]
- [x] Organize files, directories and menus for the first 3 weeks.
- [x]  Write Factorial function using classes, providing implementation of call.
- [x]  Select your own Math function. Write it in Imperative and OOP form.
- [x]  Extra Credit(1 point). Write Palindrome function using classes, must provide implementation of call. Must indicate where error occurs on front and back comparison.
