### ISSUE TITLE
Week 4: Create Task

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#7]
## Who I graded: Review Ticket [link](https://github.com/sarayu-pr11/sarayu_individual/issues/5)
| Task | Link | Check | Description | 
| --------------------- | -------------| -----------| ------------| 
| Runtime Video | [link](https://www.youtube.com/watch?v=wFyg_sEB8i8) | :heavy_check_mark: | Video of runtime for Create Task | 
| GH Pages Documentation | [link](https://christinlee367.github.io/createTask) | :heavy_check_mark: | CB Create Task completed and documented on GH Pages |
| Code |  [Full Folder](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/tree/createTaskCL/templates/pbl/CTCLPBL) , [HTML main](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/createTaskCL/templates/pbl/CTCLPBL/playlist.html) |:heavy_check_mark: | CB Create Task Code |
| Comment Code | [HTML main](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/createTaskCL/templates/pbl/CTCLPBL/playlist.html)  | :heavy_check_mark: | Code with comments: ones that I made are initialed with my name |

## Christina and Kaavya 's Pair Project
| Attempts | link | Checks |
| --------------------- | -------------| ------------------|
|Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory|  [link](https://github.com/christinlee367/womenInSTEMandDavid/commit/5f6cc3749d273a428a0d61c48d337308ffa3cdfc) | :heavy_check_mark: |
| Hack #1 | [link](https://github.com/christinlee367/womenInSTEMandDavid/blob/main/templates/KCHacksAuthorization.html) | :heavy_check_mark: |
|Hack #2, Hack #3 |  [link](https://github.com/christinlee367/womenInSTEMandDavid/blob/main/crud3/KC%20Hacks.py) |:heavy_check_mark: |

- [x] CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on **Intellij**

**Comment by sarayu-pr11** [comment]
**SCORE: 5/5 graded by Sarayu Pochimireddy**
Create Task (2 Points)
CB Create Task Coding requirements documented (1/1)
Runtime of Code(with comments) on Replit/Intellij (1/1)

Accounts and Logins (3 points)
Hack #1 Add Phone Number to Sign Up / Authorization screen (1/1)
Hack #2 Add logout to CRUD screen (1/1)
Hack #3 Add login_required to another portion of the project (1/1)
