### ISSUE TITLE
Proctored MCQ Week1 : Quiz1, Quiz2 Scores

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#9]
### Create Task code/runtime and 1 min video ([link to review ticket](https://github.com/christinlee367/christinlee367.github.io/issues/7))
- [x] create task
- [x] Finals-Quiz1 score/50 and corrections
- [x] Finals-Quiz2 score/50 and corrections
[GitHub Pages to Test Corrections](https://christinlee367.github.io/finalMCQ)

**Comment by sanvi1855544** [comment]
Make sure you have a second call. It seems you have all the requirement except for the array one. One way you can use array is possibly with the UI or you can toggle between the rows by associating an index per row.  The First Quiz had many mistakes. It is clear you ran out of time. There is significant improvement in the second quiz. The correction are well written. I would advise you to practice the algorithmic question more as it seems you are more confident in the conceptual one.

Overall good job!

4.6/5
